In [5]:
import skmob
from skmob.utils import utils, constants
from skmob.tessellation import tilers
from skmob.utils.plot import plot_gdf

import numpy as np
import pandas as pd
import geopandas as gpd
from skmob.models.gravity import Gravity


from sklearn.model_selection import train_test_split
from random import sample
import pickle
from scipy.spatial import distance
import sys

import random
random.seed(3110)

from matplotlib import pyplot as plt
plt.rcParams["figure.figsize"] = (12, 9) # (w, h)

In [6]:
city = "NYC"
transp = "Taxi"

In [7]:
with open("./"+ transp + city+ "/v_train.txt", "rb") as fp:   # Unpickling
    v_train = pickle.load(fp)
print(len(v_train))


with open("./"+ transp + city+ "/v_test.txt", "rb") as fp:   # Unpickling
    v_test = pickle.load(fp)
print(len(v_test))

584
146


In [8]:
f_max = np.max(v_train)
print(f_max)

4075


In [9]:
a = 0
fake_set = []
f_max = np.max(v_train)
 
for n in sample(v_train, len(v_test)):
    randomlist = []
    for i in range(0,(64*64)):
        r = random.randint(0,f_max)
        randomlist.append(r)
    r_a = np.array(randomlist).reshape(64,64)
    fake_set.append(r_a)

In [10]:
with open("./"+ transp+city+ "/fake_set_random.txt", "wb") as fp:   # Unpickling
    pickle.dump(fake_set,fp)

In [11]:
with open("./" +transp + city +"/fake_set_random.txt", "rb") as fp:   # Unpickling
    f_set = pickle.load(fp)

In [12]:
f_set

[array([[2333, 1988, 1426, ..., 1044, 3490,  623],
        [2195, 2563, 2936, ...,  840, 3901,  525],
        [3724, 3660, 2822, ..., 2183, 2424,  712],
        ...,
        [ 294, 1920, 3959, ..., 2241, 3612, 2249],
        [3047, 1688, 3759, ..., 2113,  146, 3439],
        [2267, 3706, 3101, ...,  900, 1873, 3568]]),
 array([[2362, 3652, 4026, ...,  219, 1718, 2193],
        [2429,  221, 2550, ...,  439, 2333, 2719],
        [2689,  920, 2643, ..., 2458, 2679,  309],
        ...,
        [2913,  488, 3854, ..., 1325, 2415, 1959],
        [3341, 2123, 3327, ...,  798, 2754, 2036],
        [1894, 3370,  418, ...,  568, 2277, 3607]]),
 array([[3310, 1817, 2657, ..., 3348,   46, 1127],
        [1341, 3457, 2086, ..., 3661, 1279, 4041],
        [ 456,  605, 1723, ...,  193, 3441,  272],
        ...,
        [1420, 2030,  988, ..., 1565, 2384, 3746],
        [2893, 2138,  649, ..., 1328, 1104, 1249],
        [3663, 1313,  289, ...,  320, 2444,  995]]),
 array([[ 277,  604, 1771, ..., 2489,

In [13]:
f_set[0]

array([[2333, 1988, 1426, ..., 1044, 3490,  623],
       [2195, 2563, 2936, ...,  840, 3901,  525],
       [3724, 3660, 2822, ..., 2183, 2424,  712],
       ...,
       [ 294, 1920, 3959, ..., 2241, 3612, 2249],
       [3047, 1688, 3759, ..., 2113,  146, 3439],
       [2267, 3706, 3101, ...,  900, 1873, 3568]])

In [14]:
f_set[0].shape

(64, 64)